/**
 * GET /api/improve?username=<username>
 *
 * Returns the Developer_Score breakdown plus a practical improvement roadmap
 * for a GitHub user.
 *
 * The roadmap is deterministic — it is derived from the measured score
 * breakdown, not generated by an AI model — so the same profile always produces
 * the same advice, and every item can be traced back to a real number.
 */

import { NextRequest, NextResponse } from "next/server";
import { getProfileAnalysis } from "@/lib/analysis-service";
import { buildRoadmap } from "@/lib/recommendations";
import { validateUsername } from "@/lib/validators";

export const dynamic = "force-dynamic";

function errorResponse(code: string, message: string, status: number) {
  return NextResponse.json({ success: false, error: { code, message } }, { status });
}

export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const validation = validateUsername(searchParams.get("username"));

  if (!validation.ok) {
    return errorResponse("VALIDATION", validation.error, 400);
  }

  const username = validation.username;

  // Reuses a recent snapshot when one exists, so navigating between the
  // leaderboard and this page does not re-hit GitHub.
  const result = await getProfileAnalysis(username);

  if (!result.ok) {
    if (result.kind === "not_found") {
      return errorResponse(
        "NOT_FOUND",
        `We could not find a GitHub user called "${username}". Check the spelling — the account may have been renamed or deleted.`,
        404,
      );
    }
    return errorResponse(
      "UPSTREAM",
      "GitHub could not be reached right now (it may be rate limiting us). Please try again in a moment.",
      502,
    );
  }

  const { analysis } = result;
  const roadmap = buildRoadmap(analysis.profile, analysis.stats, analysis.breakdown);

  return NextResponse.json({
    success: true,
    data: {
      username: analysis.username,
      login: analysis.profile.login || analysis.username,
      name: analysis.profile.name ?? null,
      avatarUrl: analysis.profile.avatarUrl ?? "",
      profileUrl:
        analysis.profile.profileUrl || `https://github.com/${analysis.username}`,
      score: analysis.score,
      grade: analysis.grade,
      tier: analysis.tier.label,
      breakdown: analysis.breakdown,
      roadmap,
    },
  });
}
